version: '3.3'
services :
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 5433:8080